const Img = {
  otpverify: require('../assets/images/otpverifyscr.png'),
  splashscr: require('./../assets/images/splashscr.png'),
  intro: require('../assets/images/introimg1.png'),
  goback: require('../assets/images/back.png'),
  headerbg: require('../assets/images/headerbg.png'),
  draw: require('../assets/images/draw.png'),
  primarylogo: require('../assets/images/primarylogo.png'),
  lcn: require('../assets/images/location.png'),
  hrt: require('../assets/images/heart.png'),
  bll: require('../assets/images/notification.png'),
  srch: require('../assets/images/search.png'),
  sttng: require('../assets/images/setting.png'),
  hstimgage: require('../assets/images/hostel.png'),
  hstdetail: require('../assets/images/hosteldetail.png'),
  locationdetail: require('../assets/images/locationnew.png'),
  verifiedicon: require('../assets/images/verified.png'),
  ratingstaricon: require('../assets/images/ratingstar.png'),
  noroomicon: require('../assets/images/noroom.png'),
  allhostelicon: require('../assets/images/allhostel.png'),
  sortbyicon: require('../assets/images/sortbyimg.png'),
  morehostelicon: require('../assets/images/morehostel.png'),
  hostellogoicon: require('../assets/images/hostellogo.png'),
  hostelrentouticon: require('../assets/images/hostelrentout.png'),
  buildingicon: require('../assets/images/build.png'),
  pword: require('../assets/images/p.png'),
  noitificationicon: require('../assets/images/notification.png'),
  walleticon: require('../assets/images/wallet.png'),
  vegetableicon: require('../assets/images/vegtable.png'),
  groceryicon: require('../assets/images/grocery.png'),
  beautyicon: require('../assets/images/Beauty.png'),
  householdicon: require('../assets/images/household.png'),
  storeimgicon: require('../assets/images/storeimg.png'),
  galleryicon: require('../assets/images/gallery.png'),
  telegramicon: require('../assets/images/telegram.png'),
  complainticon: require('../assets/images/complaint.png'), 
  attachmenticon:require('../assets/images/attachment.png'),
  tickicon:require('../assets/images/tick.png'),
  uncheckicon:require('../assets/images/uncheck.png'),
  helpicon:require('../assets/images/help.png'),
  breakfasticon:require('../assets/images/breakfast.png'),
  videoicon:require("../assets/images/video.png"),
  hostelrentoutsucess:require("../assets/images/hostelrentoutsucess.png"),
  profileicon:require("../assets/images/profile.png"),
  greentick:require("../assets/images/greentick.png"),
  lastprofileicon:require("../assets/images/lastprofile.png"),
  bellicon:require("../assets/images/bell.png"),
  lunchicon:require("../assets/images/lunch.png"),
  snackicon:require("../assets/images/snack.png"),
  lefticon:require("../assets/images/drawerarrow.png"),
  shareicon:require("../assets/images/share.png"),
  parkingicon:require("../assets/images/parking.png"),
  gymicon:require("../assets/images/gym.png"),
  msgicon:require("../assets/images/msg.png"),
  profilepicicon:require("../assets/images/profilepic.png"),
  editicon:require("../assets/images/edit.png"),
  newvideoicon:require("../assets/images/newvideo.png"),
  uncheckstaricon:require("../assets/images/uncheckstar.png"),
  Foodmenuicon:require("../assets/images/Foodmenu.png"),
  verifytickicon:require("../assets/images/verifytick.png"),
  notificationladyicon:require("../assets/images/notificationImg.png"),
  phoneiconcontact:require("../assets/images/honeicon.png"),
  msgicon:require("../assets/images/messageicon.png"),
  paydone:require("../assets/images/paysucess.png")
};

export {Img};
